[package]
name = "grahh-db"
version = "0.1.2"
edition = "2024"
publish = false

[dependencies]
chrono = "0.4.*"
postcard = { version = "1.1.*", features = ["alloc", "use-std"] }
serde = { version = "1.0.*", features = ["derive"] }
thiserror = "2.0.*"
